package exammanagementsystemf;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
/**
 *
 * @author ANTON
 */
public class adminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public adminDashboard() {
        initComponents();
        setLocationRelativeTo(null);
        
        try {
        Connection();
        loadTotalStudents();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Database connection error: " + ex.getMessage());
    }
}
    
     Connection con;
    Statement st;
    
    public static final String DbName = "exammanagementsystem";
    private static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbUrl = "jdbc:mysql://localhost:3306/"+DbName;
    private static final String DbUsername = "root";
    private static final String DbPassword = "";
    
    public void Connection() throws SQLException {
    try {
        Class.forName(DbDriver);
        con = DriverManager.getConnection(DbUrl, DbUsername, DbPassword);
        st = con.createStatement();

        if (con != null) {
            System.out.println("Dashboard Connection Successful");
        }
    } catch (ClassNotFoundException ex) {
        System.getLogger(adminDashboard.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
    }
}
    public void loadTotalStudents() {
    try {
        String sql = "SELECT COUNT(*) AS total FROM accountStudents";
        ResultSet rs = st.executeQuery(sql);

        if (rs.next()) {
            totalStudents.setText(rs.getString("total"));
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading total students: " + e.getMessage());
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        totalExam = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        totalStudents = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAdminUMDashboard = new javax.swing.JButton();
        btnAdminUMLogout = new javax.swing.JButton();
        btnAdminDashboardUM = new javax.swing.JButton();
        btnAdminUMExams = new javax.swing.JButton();
        btnAdminUMResults = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(230, 238, 248));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(196, 214, 235));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\test (1).png")); // NOI18N
        jLabel5.setText("Total Exams");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        totalExam.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        totalExam.setForeground(new java.awt.Color(51, 51, 51));
        totalExam.setText("01");
        jPanel3.add(totalExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 140, 80));

        jPanel4.setBackground(new java.awt.Color(196, 214, 235));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\users-alt.png")); // NOI18N
        jLabel4.setText("Total Students");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        totalStudents.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        totalStudents.setForeground(new java.awt.Color(51, 51, 51));
        totalStudents.setText("01");
        jPanel4.add(totalStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 40, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 140, 80));

        jPanel5.setBackground(new java.awt.Color(196, 214, 235));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\pending.png")); // NOI18N
        jLabel7.setText("Pending Exams");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("01");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 140, 80));

        jPanel6.setBackground(new java.awt.Color(196, 214, 235));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\books.png")); // NOI18N
        jLabel6.setText("Total Subjects");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("01");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 40));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 140, 80));

        jTable1.setBackground(new java.awt.Color(160, 184, 210));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Exam Taken", "Username", "Password"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 197, 660, 290));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Recent Activities");
        jLabel8.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jLabel8ComponentHidden(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 700, 500));

        jPanel1.setBackground(new java.awt.Color(71, 85, 105));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdminUMDashboard.setBackground(new java.awt.Color(30, 41, 59));
        btnAdminUMDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminUMDashboard.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\dashboard-panel.png")); // NOI18N
        btnAdminUMDashboard.setText("Dashboard");
        btnAdminUMDashboard.addActionListener(this::btnAdminUMDashboardActionPerformed);
        jPanel1.add(btnAdminUMDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, 50));

        btnAdminUMLogout.setText("Logout");
        jPanel1.add(btnAdminUMLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 170, 30));

        btnAdminDashboardUM.setBackground(new java.awt.Color(30, 41, 59));
        btnAdminDashboardUM.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminDashboardUM.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\user-gear.png")); // NOI18N
        btnAdminDashboardUM.setText("User Management");
        btnAdminDashboardUM.addActionListener(this::btnAdminDashboardUMActionPerformed);
        jPanel1.add(btnAdminDashboardUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, 50));

        btnAdminUMExams.setBackground(new java.awt.Color(30, 41, 59));
        btnAdminUMExams.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminUMExams.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\test.png")); // NOI18N
        btnAdminUMExams.setText("Exams");
        btnAdminUMExams.addActionListener(this::btnAdminUMExamsActionPerformed);
        jPanel1.add(btnAdminUMExams, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, 50));

        btnAdminUMResults.setBackground(new java.awt.Color(30, 41, 59));
        btnAdminUMResults.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminUMResults.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\chart-simple-horizontal.png")); // NOI18N
        btnAdminUMResults.setText("Results");
        btnAdminUMResults.addActionListener(this::btnAdminUMResultsActionPerformed);
        jPanel1.add(btnAdminUMResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\ExamMSystem.Images\\admin.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Admin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(30, 41, 59));
        jButton1.setText("Logout");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 170, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 500));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\Download CURVE WAVE ABSTRACT BACKGROUND BLUE CYAN for free.jpg")); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAdminUMDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUMDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminUMDashboardActionPerformed

    private void jLabel8ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabel8ComponentHidden
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel8ComponentHidden

    private void btnAdminDashboardUMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminDashboardUMActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new adminUserManagement().setVisible(true);
    }//GEN-LAST:event_btnAdminDashboardUMActionPerformed

    private void btnAdminUMExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUMExamsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new adminExams().setVisible(true);
    }//GEN-LAST:event_btnAdminUMExamsActionPerformed

    private void btnAdminUMResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUMResultsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new adminResults().setVisible(true);
    }//GEN-LAST:event_btnAdminUMResultsActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);
        int a = JOptionPane.showConfirmDialog(jf, "Do you really want to logout?", "select", JOptionPane.YES_NO_OPTION);
        if (a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminDashboardUM;
    private javax.swing.JButton btnAdminUMDashboard;
    private javax.swing.JButton btnAdminUMExams;
    private javax.swing.JButton btnAdminUMLogout;
    private javax.swing.JButton btnAdminUMResults;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel totalExam;
    private javax.swing.JLabel totalStudents;
    // End of variables declaration//GEN-END:variables
}
