/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exammanagementsystemf;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ANTON
 */
public class adminExams extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(adminExams.class.getName());

    /**
     * Creates new form adminExams
     */
    public adminExams() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAdminUMLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAdminUMResults = new javax.swing.JButton();
        btnAdminUMExams = new javax.swing.JButton();
        btnAdminUMUserManagement = new javax.swing.JButton();
        btnAdminUMDashboard = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(230, 238, 248));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(210, 225, 245));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setBackground(new java.awt.Color(175, 195, 225));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Networking", "Programming" }));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 150, -1));

        jLabel3.setText("Subject");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel4.setText("Exam Duration");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(175, 195, 225));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30mins", "40mins", "50min", "1hr", " ", " " }));
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, -1));
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, -1));

        jTextField6.setBackground(new java.awt.Color(175, 195, 225));
        jTextField6.setText("Enter Question...");
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 270, -1));

        jLabel13.setText("A.");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jTextField7.setBackground(new java.awt.Color(175, 195, 225));
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 250, -1));

        jLabel14.setText("B.");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jTextField8.setBackground(new java.awt.Color(175, 195, 225));
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 250, -1));

        jTextField9.setBackground(new java.awt.Color(175, 195, 225));
        jPanel3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 250, -1));

        jLabel15.setText("C.");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jLabel16.setText("D.");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jTextField10.setBackground(new java.awt.Color(175, 195, 225));
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 250, -1));

        jLabel17.setText("Correct Answer:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, -1));

        jTextField11.setBackground(new java.awt.Color(175, 195, 225));
        jPanel3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 50, -1));

        jButton2.setBackground(new java.awt.Color(120, 150, 200));
        jButton2.setText("Save");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 70, -1));

        jButton3.setBackground(new java.awt.Color(100, 130, 180));
        jButton3.setText("Edit");
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 70, -1));

        jButton4.setBackground(new java.awt.Color(100, 130, 180));
        jButton4.setText("Delete");
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 70, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 670, 180));

        jTable1.setBackground(new java.awt.Color(200, 220, 245));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No.", "Subject ID", "Subject", "Question", "Answer"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 670, 270));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, -20, 40, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 710, 500));

        jPanel1.setBackground(new java.awt.Color(71, 85, 105));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdminUMLogout.setText("Logout");
        jPanel1.add(btnAdminUMLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 170, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\ExamMSystem.Images\\admin.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Admin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        btnAdminUMResults.setBackground(new java.awt.Color(30, 41, 59));
        btnAdminUMResults.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminUMResults.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\chart-simple-horizontal.png")); // NOI18N
        btnAdminUMResults.setText("Results");
        btnAdminUMResults.addActionListener(this::btnAdminUMResultsActionPerformed);
        jPanel1.add(btnAdminUMResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 50));

        btnAdminUMExams.setBackground(new java.awt.Color(30, 41, 59));
        btnAdminUMExams.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminUMExams.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\test.png")); // NOI18N
        btnAdminUMExams.setText("Exams");
        btnAdminUMExams.addActionListener(this::btnAdminUMExamsActionPerformed);
        jPanel1.add(btnAdminUMExams, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 170, 50));

        btnAdminUMUserManagement.setBackground(new java.awt.Color(30, 41, 59));
        btnAdminUMUserManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminUMUserManagement.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\user-gear.png")); // NOI18N
        btnAdminUMUserManagement.setText("User Management");
        btnAdminUMUserManagement.addActionListener(this::btnAdminUMUserManagementActionPerformed);
        jPanel1.add(btnAdminUMUserManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 170, 50));

        btnAdminUMDashboard.setBackground(new java.awt.Color(30, 41, 59));
        btnAdminUMDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminUMDashboard.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\dashboard-panel.png")); // NOI18N
        btnAdminUMDashboard.setText("Dashboard");
        btnAdminUMDashboard.addActionListener(this::btnAdminUMDashboardActionPerformed);
        jPanel1.add(btnAdminUMDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, 50));

        jButton1.setBackground(new java.awt.Color(30, 41, 59));
        jButton1.setText("Logout");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 170, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 500));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\Download CURVE WAVE ABSTRACT BACKGROUND BLUE CYAN for free.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminUMDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUMDashboardActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new adminDashboard().setVisible(true);
    }//GEN-LAST:event_btnAdminUMDashboardActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);
        int a = JOptionPane.showConfirmDialog(jf, "Do you really want to logout?", "select", JOptionPane.YES_NO_OPTION);
        if (a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAdminUMUserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUMUserManagementActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new adminUserManagement().setVisible(true);
    }//GEN-LAST:event_btnAdminUMUserManagementActionPerformed

    private void btnAdminUMExamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUMExamsActionPerformed
        // TODO add your handling code here:
        setVisible(true);
    }//GEN-LAST:event_btnAdminUMExamsActionPerformed

    private void btnAdminUMResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminUMResultsActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new adminResults().setVisible(true);
    }//GEN-LAST:event_btnAdminUMResultsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new adminExams().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminUMDashboard;
    private javax.swing.JButton btnAdminUMExams;
    private javax.swing.JButton btnAdminUMLogout;
    private javax.swing.JButton btnAdminUMResults;
    private javax.swing.JButton btnAdminUMUserManagement;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
