/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exammanagementsystemf;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ANTON
 */
public class studentDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(studentDashboard.class.getName());
    Connection con;
    Statement st;
    int studentId;
    
    /**
     * Creates new form studentDashboard
     */
    public studentDashboard(int studentId) {
    initComponents();
    setLocationRelativeTo(null);
    loadAvailableExams();
    loadResults();

    btnEdit.setBackground(new java.awt.Color(120, 135, 155));
    btnEdit.setText("Edit Info");
    btnEdit.addActionListener(this::btnEditActionPerformed);
    jPanel7.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, -1));  
    
    this.studentId = studentId;

    try {
        Connection();
        loadStudentInfo();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    public void loadStudentInfo() {
    try {
        String sql = "SELECT * FROM accountStudents student_id =?";
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setInt(1, studentId);
        ResultSet rs = st.executeQuery(sql);

        if (rs.next()) {
            txtName.setText(rs.getString("username"));
            jLabel25.setText(rs.getString("student_id"));
            txtSection.setText(rs.getString("section"));

            String course = rs.getString("course");
            if (course == null || course.trim().isEmpty()) {
                jLabel27.setText("N/A");
            } else {
                jLabel27.setText(course);
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading student info: " + e.getMessage());
    }
}
    
    public void Connection() throws Exception {
    Class.forName("com.mysql.cj.jdbc.Driver");
    con = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/exammanagementsystem",
        "root",
        ""
    );
    st = con.createStatement();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAvailableExams = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblExamResults = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAdminUMLogout = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Section = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        txtName = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtSection = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnTakeExam = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel7.setText("jLabel7");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setText("01");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(230, 238, 248));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(185, 192, 202));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(196, 214, 235));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Pending");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Exams");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setText("01");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 140, 70));

        jPanel9.setBackground(new java.awt.Color(196, 214, 235));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Total Exams");
        jPanel9.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Taken");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setText("01");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 70));

        jPanel10.setBackground(new java.awt.Color(196, 214, 235));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Upcoming");
        jPanel10.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Exams");
        jPanel10.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("01");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 140, 70));

        jPanel11.setBackground(new java.awt.Color(196, 214, 235));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Average");
        jPanel11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Score");
        jPanel11.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("01");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 140, 70));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Available Exams");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        tblAvailableExams.setBackground(new java.awt.Color(170, 178, 190));
        tblAvailableExams.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject", "Status", "Duration"
            }
        ));
        jScrollPane2.setViewportView(tblAvailableExams);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 680, 140));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 680, 250));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Exam Results");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 6, -1, -1));

        tblExamResults.setBackground(new java.awt.Color(170, 178, 190));
        tblExamResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Subject", "Score", "Status"
            }
        ));
        jScrollPane5.setViewportView(tblExamResults);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 680, 170));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 680, 200));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 700, 500));

        jPanel3.setBackground(new java.awt.Color(71, 85, 110));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdminUMLogout.setText("Logout");
        jPanel3.add(btnAdminUMLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 170, 30));

        btnLogout.setBackground(new java.awt.Color(30, 41, 59));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
        jPanel3.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 170, 30));

        jPanel7.setBackground(new java.awt.Color(102, 132, 171));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Student");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        name.setText("Name:");
        jPanel7.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setText("Student ID:");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        Section.setText("Section:");
        jPanel7.add(Section, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel6.setText("Course:");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        btnEdit.setBackground(new java.awt.Color(120, 135, 155));
        btnEdit.setText("Edit Info");
        btnEdit.addActionListener(this::btnEditActionPerformed);
        jPanel7.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 80, -1));

        btnChange.setBackground(new java.awt.Color(120, 135, 155));
        btnChange.setText("Change Pass");
        btnChange.addActionListener(this::btnChangeActionPerformed);
        jPanel7.add(btnChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        txtName.setText("Name");
        jPanel7.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 150, -1));

        jLabel25.setText("Student_ID");
        jPanel7.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 130, -1));

        txtSection.setText("Section");
        jPanel7.add(txtSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 140, -1));

        jLabel27.setText("Course");
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 140, -1));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 260));

        btnTakeExam.setBackground(new java.awt.Color(78, 100, 110));
        btnTakeExam.setText("Take Exam");
        btnTakeExam.addActionListener(this::btnTakeExamActionPerformed);
        jPanel3.add(btnTakeExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 210, 500));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, 170));
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadAvailableExams(){
        try{
            String sql = "SELECT subject, status, duration FROM exams";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel) tblAvailableExams.getModel();
            model.setRowCount(0);
            
            while (rs.next()){
                model.addRow(new Object[]{
                    rs.getString("subject"),
                    rs.getString("status"),
                    rs.getString("duration")
                });
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void loadResults(){
        try{
            String sql = "SELECT subject, score, status FROM results WHERE student_id=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, studentId);
            
            ResultSet rs = pst.executeQuery();
            
            DefaultTableModel model = (DefaultTableModel) tblExamResults.getModel();
            model.setRowCount(0);
            
            while (rs.next()){
                model.addRow(new Object []{
                    rs.getString("subject"),
                    rs.getString("score"),
                    rs.getString("status")
                });
            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
        
    
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        JFrame jf = new JFrame();
        jf.setAlwaysOnTop(true);
        int a = JOptionPane.showConfirmDialog(jf, "Do you really want to logout?", "select", JOptionPane.YES_NO_OPTION);
        if (a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        
        
        String newName = JOptionPane.showInputDialog(this, "Enter new username:", txtName.getText());
    if (newName == null) return;

    String newSection = JOptionPane.showInputDialog(this, "Enter new section:", txtSection.getText());
    if (newSection == null) return;

    String currentCourse = jLabel27.getText().equals("N/A") ? "" : jLabel27.getText();
    String newCourse = JOptionPane.showInputDialog(this, "Enter your course:", currentCourse);
    if (newCourse == null) return;

    if (newName.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username cannot be empty.");
        return;
    }

    if (newSection.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Section cannot be empty.");
        return;
    }

     try {
        String name = txtName.getText();
        String section = txtSection.getText();

        if (name.isEmpty() || section.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fill all fields!");
            return;
        }

        String sql = "UPDATE accountStudents SET username=?, section=? WHERE student_id=?";
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, name);
        pst.setString(2, section);
        pst.setInt(3, studentId);

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Profile Updated!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        // TODO add your handling code here:
        try {
        String oldPass = JOptionPane.showInputDialog(this, "Enter Old Password:");
        String newPass = JOptionPane.showInputDialog(this, "Enter New Password:");
        String confirmPass = JOptionPane.showInputDialog(this, "Confirm New Password:");

        if (oldPass == null || newPass == null || confirmPass == null) return;

        if (!newPass.equals(confirmPass)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match!");
            return;
        }

        String sql = "SELECT * FROM accountStudents WHERE student_id=? AND password=?";
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setInt(1, studentId);
        pst.setString(2, oldPass);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {

            sql = "UPDATE accountStudents SET password=? WHERE student_id=?";
            pst = con.prepareStatement(sql);

            pst.setString(1, newPass);
            pst.setInt(2, studentId);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Password Changed!");

        } else {
            JOptionPane.showMessageDialog(this, "Wrong old password!");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnTakeExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTakeExamActionPerformed
        // TODO add your handling code here:
        int row = tblAvailableExams.getSelectedRow();
                
                if (row == -1){
                    JOptionPane.showMessageDialog(this, "Select exam first!");
                    return;
                }
                String subject = tblAvailableExams.getValueAt(row, 0).toString();
                
                new studentExamInterface(studentId, subject).setVisible(true);
                this.dispose();;
    }//GEN-LAST:event_btnTakeExamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new studentDashboard(1).setVisible(true));    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Section;
    private javax.swing.JButton btnAdminUMLogout;
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnTakeExam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel name;
    private javax.swing.JTable tblAvailableExams;
    private javax.swing.JTable tblExamResults;
    private javax.swing.JLabel txtName;
    private javax.swing.JLabel txtSection;
    // End of variables declaration//GEN-END:variables
}
