/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exammanagementsystemf;

/**
 *
 * @author ANTON
 */
public class studentExamInterfaceMid extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(studentExamInterfaceMid.class.getName());

    /**
     * Creates new form studentExamInterfaceMid
     */
    public studentExamInterfaceMid() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        question = new javax.swing.JLabel();
        btnC = new javax.swing.JButton();
        btnD = new javax.swing.JButton();
        btnB = new javax.swing.JButton();
        btnA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Question 1 of 10");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        btnNext.setText("Next");
        jPanel1.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 70, -1));

        btnSubmit.setText("Submit");
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, -1));

        question.setBackground(new java.awt.Color(255, 255, 255));
        question.setText("Enter Question...");
        question.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        question.setOpaque(true);
        jPanel1.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 420, 130));

        btnC.setText("C.");
        btnC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnC.addActionListener(this::btnCActionPerformed);
        jPanel1.add(btnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 420, -1));

        btnD.setText("D.");
        btnD.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnD.addActionListener(this::btnDActionPerformed);
        jPanel1.add(btnD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 420, -1));

        btnB.setText("B.");
        btnB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 420, -1));

        btnA.setText("A.");
        btnA.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(btnA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 420, -1));

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 490, 440));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCActionPerformed

    private void btnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new studentExamInterfaceMid().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnA;
    private javax.swing.JButton btnB;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnD;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel question;
    // End of variables declaration//GEN-END:variables
}
