/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exammanagementsystemf;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author ANTON
 */
public class login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(login.class.getName());
    
    /**
     * Creates new form Login
     */
    public login() {
        initComponents();
        
        JPanel1.setBackground(new java.awt.Color(255, 255, 255, 60));
        try {
            Connection();
        } catch (SQLException ex) {
            System.getLogger(login.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        getRootPane().setDefaultButton(btnLogin);
        setLocationRelativeTo(null);
    }
    
    Connection con;
    Statement st;
    PreparedStatement pst;
    
    public static final String DbName = "exammanagementsystem";
    private static final String DbDriver = "com.mysql.cj.jdbc.Driver";
    private static final String DbUrl = "jdbc:mysql://localhost:3306/"+DbName;
    private static final String DbUsername = "root";
    private static final String DbPassword = "";
    
    public void Connection() throws SQLException{
        try {
            Class.forName(DbDriver);
            con = DriverManager.getConnection(DbUrl, DbUsername, DbPassword);
            st = con.createStatement();
            if(con !=null){
                System.out.println("Connection Successful");
            }
        } catch (ClassNotFoundException ex) {
            System.getLogger(register.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtUsernameLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPasswordLogin = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnLoginExit = new javax.swing.JButton();
        JPanel1 = new RoundedPanel(67);
        btnRegister = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        txtUsernameLogin.setBackground(new java.awt.Color(255, 255, 255));
        txtUsernameLogin.addActionListener(this::txtUsernameLoginActionPerformed);
        txtUsernameLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsernameLoginKeyPressed(evt);
            }
        });
        getContentPane().add(txtUsernameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 200, -1));

        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, -1, -1));

        txtPasswordLogin.setBackground(new java.awt.Color(255, 255, 255));
        txtPasswordLogin.addActionListener(this::txtPasswordLoginActionPerformed);
        txtPasswordLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordLoginKeyPressed(evt);
            }
        });
        getContentPane().add(txtPasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 200, -1));

        btnLogin.setBackground(new java.awt.Color(0, 150, 160));
        btnLogin.setForeground(new java.awt.Color(51, 51, 51));
        btnLogin.setText("Login");
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 200, -1));

        btnLoginExit.setBackground(new java.awt.Color(0, 150, 160));
        btnLoginExit.setForeground(new java.awt.Color(51, 51, 51));
        btnLoginExit.setText("Exit");
        getContentPane().add(btnLoginExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 60, -1));

        btnRegister.setBackground(new java.awt.Color(0, 150, 160));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(51, 51, 51));
        btnRegister.setText("Register");
        btnRegister.addActionListener(this::btnRegisterActionPerformed);

        jLabel5.setText("Don't have an account?");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Log In");

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegister)
                .addGap(29, 29, 29))
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 320, Short.MAX_VALUE)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        getContentPane().add(JPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 340, 420));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\download.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new register().setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsernameLogin.getText();
        String password = new String(txtPasswordLogin.getPassword());

        String studentQuery = "SELECT * FROM accountStudents WHERE username = ? AND password = ?";
        String adminQuery   = "SELECT * FROM accountdetails WHERE accUsername = ? AND accPassword = ?";

        try {
            pst = con.prepareStatement(studentQuery);
            pst.setString(1, username);
            pst.setString(2, password);

            ResultSet rs = pst.executeQuery();

        if (rs.next()) {
    JOptionPane.showMessageDialog(null, "Student login successful");

    int studentId = rs.getInt("student_id");

    new studentDashboard(studentId).setVisible(true);
    this.dispose();
    return;
}

            pst = con.prepareStatement(adminQuery);
            pst.setString(1, username);
            pst.setString(2, password);

            rs = pst.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(null, "Admin login successful");

        new adminDashboard().setVisible(true);
        this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Invalid credentials");
        }   

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsernameLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameLoginKeyPressed
        // TODO add your handling code here:
       if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        txtPasswordLogin.requestFocusInWindow();
    }
        
    }//GEN-LAST:event_txtUsernameLoginKeyPressed

    private void txtPasswordLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordLoginActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPasswordLoginActionPerformed

    private void txtPasswordLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordLoginKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        btnLogin.requestFocusInWindow();
        }
    }//GEN-LAST:event_txtPasswordLoginKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginExit;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtPasswordLogin;
    private javax.swing.JTextField txtUsernameLogin;
    // End of variables declaration//GEN-END:variables
}
